apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-eureka-discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-consul-discovery
  template:
    metadata:
      labels:
        app: bookstore-consul-discovery
    spec:
      containers:
      - name: consul
        image: consul
        ports:
        - containerPort: 8500
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-eureka-discovery-service
spec:
  selector:
    app: bookstore-consul-discovery
  ports:
    - protocol: TCP
      port: 8500
      targetPort: 8500
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-api-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-zuul-api-gateway-server
  template:
    metadata:
      labels:
        app: bookstore-zuul-api-gateway-server
    spec:
      containers:
      - name: bookstore-zuul-api-gateway-server
        image: bookstore-zuul-api-gateway-server
        ports:
        - containerPort: 8765
        env:
        - name: SERVER_PORT
          value: "8765"
        - name: ZIPKIN_HOST
          value: "bookstore-zipkin:9411"
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-api-gateway-service
spec:
  selector:
    app: bookstore-zuul-api-gateway-server
  ports:
    - protocol: TCP
      port: 8765
      targetPort: 8765
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-account-service
  template:
    metadata:
      labels:
        app: bookstore-account-service
    spec:
      containers:
      - name: bookstore-account-service
        image: bookstore-account-service
        ports:
        - containerPort: 4001
        env:
        - name: SERVER_PORT
          value: "4001"
        - name: ZIPKIN_HOST
          value: "bookstore-zipkin:9411"
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-account-service
spec:
  selector:
    app: bookstore-account-service
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-billing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-billing-service
  template:
    metadata:
      labels:
        app: bookstore-billing-service
    spec:
      containers:
      - name: bookstore-billing-service
        image: bookstore-billing-service
        ports:
        - containerPort: 5001
        env:
        - name: SERVER_PORT
          value: "5001"
        - name: ZIPKIN_HOST
          value: "bookstore-zipkin:9411"
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-billing-service
spec:
  selector:
    app: bookstore-billing-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-catalog-service
  template:
    metadata:
      labels:
        app: bookstore-catalog-service
    spec:
      containers:
      - name: bookstore-catalog-service
        image: bookstore-catalog-service
        ports:
        - containerPort: 6001
        env:
        - name: SERVER_PORT
          value: "6001"
        - name: ZIPKIN_HOST
          value: "bookstore-zipkin:9411"
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-catalog-service
spec:
  selector:
    app: bookstore-catalog-service
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-order-service
  template:
    metadata:
      labels:
        app: bookstore-order-service
    spec:
      containers:
      - name: bookstore-order-service
        image: bookstore-order-service
        ports:
        - containerPort: 7001
        env:
        - name: SERVER_PORT
          value: "7001"
        - name: ZIPKIN_HOST
          value: "bookstore-zipkin:9411"
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-order-service
spec:
  selector:
    app: bookstore-order-service
  ports:
    - protocol: TCP
      port: 7001
      targetPort: 7001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-payment-service
  template:
    metadata:
      labels:
        app: bookstore-payment-service
    spec:
      containers:
      - name: bookstore-payment-service
        image: bookstore-payment-service
        ports:
        - containerPort: 8001
        env:
        - name: SERVER_PORT
          value: "8001"
        - name: ZIPKIN_HOST
          value: "bookstore-zipkin:9411"
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-payment-service
spec:
  selector:
    app: bookstore-payment-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
